INSERT INTO arcade_directory (business_name, address, mall_center, city, state, zip, mall) VALUES ('JUST FUN', '591  MEMORIAL DR.', 'FAIRFIELD MALL', 'CHICOPEE FALLS', 'MA', '01020-5007', 1);
INSERT INTO arcade_directory (business_name, address, mall_center, city, state, zip, mall) VALUES ('STAR MUSIC', '27  MEADOW RD.', NULL, 'EAST LONGMEADOW', 'MA', '01028-', 0);
INSERT INTO arcade_directory (business_name, address, mall_center, city, state, zip, mall) VALUES ('DREAM MACHINE', '341  RUSSELL ST.', 'HAMPSHIRE MALL', 'HADLEY', 'MA', '01035-9528', 1);
INSERT INTO arcade_directory (business_name, address, mall_center, city, state, zip, mall) VALUES ('JUST FUN', '335  RUSSELL ST.', 'MOUNTAIN FARMS MALL', 'HADLEY', 'MA', '01035-9547', 1);
INSERT INTO arcade_directory (business_name, address, mall_center, city, state, zip, mall) VALUES ('PIONEER VALLEY AMUSEMENT', '90  SARGENT', NULL, 'HOLYOKE', 'MA', '01040-', 0);
INSERT INTO arcade_directory (business_name, address, mall_center, city, state, zip, mall) VALUES ('JUST GAMES', NULL, 'HOLYOKE MALL', 'HOLYOKE', 'MA', '01040-', 1);
INSERT INTO arcade_directory (business_name, address, mall_center, city, state, zip, mall) VALUES ('FUN TOO', '50  WHITING FARMS RD. EXT.', 'INGLESIDE MALL', 'HOLYOKE', 'MA', '01040-2703', 1);
INSERT INTO arcade_directory (business_name, address, mall_center, city, state, zip, mall) VALUES ('RUSSELL-HALL VENDING SERVICE', '116  RACE ST.', NULL, 'HOLYOKE', 'MA', '01040-5892', 0);
INSERT INTO arcade_directory (business_name, address, mall_center, city, state, zip, mall) VALUES ('BECKER AMUSEMENT', '75  STATE ST., P O BOX 405', NULL, 'LUDLOW', 'MA', '01056-0405', 0);
INSERT INTO arcade_directory (business_name, address, mall_center, city, state, zip, mall) VALUES ('SKOP VENDING SERVICE', '120  NORTHWEST RD.', NULL, 'WESTFIELD', 'MA', '01085-', 0);
